package com.mridx.androidtemplate.utils

const val SPLASH_DURATION: Long = 500L // 500 millisecond

const val ULB = "ulb"
const val ULB_ID = "ulb_id"
const val DISTRICT = "district"
const val DISTRICT_ID = "district_id"
const val LOGGED_IN = "logged_in"
const val TOKEN = "token"
const val UUID = "uuid"
const val USER_ID = "user_id"
const val USER_NAME = "user_name"
const val USER_EMAIL = "user_email"
const val ROLE = "role"
const val GENDER = "gender"
const val ADDRESS = "address"
const val BIO = "bio"
const val DOB = "dob"
const val PHOTO = "photo"
const val PHONE = "phone"
const val LAST_UPDATED = "last_updated"
const val DESIGNATION = "designation"
const val JOINED = "joined"
const val CURRENT_APP_VERSION = "app_version"
const val LAC = "lac"
const val DIVISION = "division"
const val NEW_DIVISION = "new_division"
const val WORKING_DIVISION = "working_division"

const val FIREBASE_STORAGE = "https://firebasestorage.googleapis.com"
const val BUCKET = "/v0/b/pbga-app.appspot.com/o/"
const val MEDIA = "?alt=media"
const val METER_READING_IMAGE_DIR = "meter_reading_images/"
const val SITE_IMAGE_DIR = "site_images/"
const val SERVICE_METER_IMAGE_DIR = "service_meter_images/"
const val METER_INSTALLATION_IMAGE_DIR = "meter_installation_images/"

const val METER_INSTALLATION_SITE_IMAGE = "${METER_INSTALLATION_IMAGE_DIR}site_image_"
const val METER_INSTALLATION_METER_IMAGE = "${METER_INSTALLATION_IMAGE_DIR}meter_image_"
const val METER_READING_METER_IMAGE = "${METER_READING_IMAGE_DIR}meter_image_"